# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: taiwotherock2@gmail.com
author_name: Taiwo Ojo
contract_name: nftcreditscore
deployment_language: python
preset_name: production
project_name: algnftcreditscore

